// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/lhaaso/liushuo/WFCTAMC-v5.1.3.6-260818/./src/wtelescope.cc";

#endif
